/* This file is auto-generated by Rake */

/* Build Host Info:
 * - Host Name: runner-1dzsgzyq-project-50-concurrent-0
 * - Kernel Build: Linux version 5.15.0-92-generic (buildd@lcy02-amd64-002) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #102~20.04.1-Ubuntu SMP Mon Jan 15 13:09:14 UTC 2024
 * - Build Timestamp: 2024-02-18 16:49:45 +0000
 * - Ruby Version: ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
 * - Rake Version: rake, version 13.0.3
 */

/*
 * Source Control Info:
 * - Submodule:
 *    6503144964c1f305f192dd6e9aa36d02496bfe14 emrun (6503144)
 */

#ifndef __NUCLEI_SEGGER_RTL_RELEASE_H
#define __NUCLEI_SEGGER_RTL_RELEASE_H 1

#define __NUCLEI_SEGGER_RTL_RELEASE_COMMIT "c31561de81dfb4aeb352f2153a69ed6ae3957941"

#endif /* __NUCLEI_SEGGER_RTL_RELEASE_H */
